import SideBar from "@/components/SideBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="bg-neutral-900 text-neutral-100 h-screen w-screen">
        <div className="flex align-top max-w-6xl mx-auto gap-5">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
